### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by tvwenger** [Archaegeo/Archaegeo-Orbital-Hud#123]
Hello! I got the attached error message just now while flying through space. I wasn't doing anything in particular, and I haven't seen it before. This is probably just a fluke, but nonetheless I hope this is useful for debugging!

![Capture](https://user-images.githubusercontent.com/5921304/148628650-254899fe-ad29-45f8-87e5-ad383bbf7ac1.PNG)

**Comment by Archaegeo** [comment]
Please update to 1.702 and let me know if it repeats.

**Comment by Archaegeo** [comment]
Closing due to no follow on.
