### ISSUE TITLE
AtmoSpeedLimit doesn't allow some types of ships to leave atmosphere.

### ISSUE THREAD

**Issue by skiz** [Archaegeo/Archaegeo-Orbital-Hud#134]
I am flying a S core ship and as I near the breakpoint of ~3% atmosphere (4500m), my speed increases (high altitude lift) quite quickly.
This increases my speed, but the speed limiter hits the brakes and stops my ship from climbing out, causing a stall.

This doesn't always happen, but enough to be a major pain in the gas.
My current workaround:  Set default limit to 10000 in lua. (but basically breaks limiting all together).

Proposed Fix #1:  when scrolling to the max limit, there should be 1 more option beyond that is [DISABLED]
Proposed Fix #2: when amos && atmos < 5%, disable speed limiter
Proposed Fix #3: Hot key to disable speed limiter, or cycle modes.

**Comment by Archaegeo** [comment]
Right now the limiter does cut out in atmo, but it does it at a very low % atmo, like <0.5% Atmo.  The problem with changing that is that some ships burn up in planets where that atmo continues for a bit and if they have strong engines. 
Ill think on making a quick way to disable the limiter or alt-mousewheel > limit
