### ISSUE TITLE
Fix AxisCommand thrust calculation for space only ship

### ISSUE THREAD

**Issue by leniver** [Archaegeo/Archaegeo-Orbital-Hud#137]
AxisCommand has a bug for a long time.

From 0.1% to 9% atmospheric, the thrust is taken from the atmospheric engines.
On normal ships, this have only a small impact, but bigger the size difference between space and atmo engine is bigger the issue is.
And if you have a space only ship, you will simply have no thrust on your space engine.

AxisCommand.lua (line 340)
```
    if (inspace == 0) then    
        if (axisThrottle > 0) then
            local maxAtmoForceForward = maxKPAlongAxis[1]
            forceCorrespondingToThrottle = axisThrottle * maxAtmoForceForward
        else
            local maxAtmoForceBackward = maxKPAlongAxis[2]
            forceCorrespondingToThrottle = -axisThrottle * maxAtmoForceBackward
        end
    else
        if (axisThrottle > 0) then
            local maxSpaceForceForward = maxKPAlongAxis[3]
            forceCorrespondingToThrottle = axisThrottle * maxSpaceForceForward
        else
            local maxSpaceForceBackward = maxKPAlongAxis[4]
            forceCorrespondingToThrottle = -axisThrottle * maxSpaceForceBackward
        end
    end
```

The best way to solve this problem would be to not use this function to calculate the thrust and to define the space and atmospheric thrust independently
The easy way of fixing it is to override the function `composeAxisAccelerationFromThrottle` and make sure that if the atmospheric thrust is 0 it will return the space one. (or the max value of both)

**Comment by Archaegeo** [comment]
Fixed in 1.717
