### ISSUE TITLE
Throttle jumps all over the place.

### ISSUE THREAD

**Issue by Anitalex** [Archaegeo/Archaegeo-Orbital-Hud#141]
I am flying and I scroll back and I get that I am at 50% but my engines are off.
![image](https://user-images.githubusercontent.com/13589604/150048928-39c165d3-2610-41b5-9b9c-852fc8b26841.png)

One wheel click forward and it goes to 10% but the engines are at 100%
![image](https://user-images.githubusercontent.com/13589604/150048912-ddf336d1-698a-471a-8774-5254e733e86f.png)

**Comment by Anitalex** [comment]
![image](https://user-images.githubusercontent.com/13589604/150050190-d7f0f147-8e0f-46dd-b4c4-4ea45845fb3e.png)

**Comment by Anitalex** [comment]
In that last one my forward speed is increasing but at -5%

**Comment by Archaegeo** [comment]
Fixed to 10% in 1.709 when not in AtmoSpeedAssist as you are.
