### ISSUE TITLE
Will not allow others to use.

### ISSUE THREAD

**Issue by Narantus** [Archaegeo/Archaegeo-Orbital-Hud#165]
I install this new version, and none of my other Org. members can use it. I don't know if it's broken, or if they need it installed as well. Hope this gets fixed in the future. If so, please let me know.

**Comment by Archaegeo** [comment]
For others to use your ship they must either have the require files in the correct path if using the 8kb ArchHUD.conf (1.7XX) or you can install the 180k ArchHUDGFN.conf version (0.7XX).
