### ISSUE TITLE
Radar

### ISSUE THREAD

**Issue by ghost1257** [Archaegeo/Archaegeo-Orbital-Hud#180]
When I enter my ship in the lua chat box it says there was an error with the radars? I am just reporting this. in the picture I have the chat box if you can read it that has the error. I am using the latest version and using Nividia Now
![Dual Universe 2022 05 23 - 14 35 55 01](https://user-images.githubusercontent.com/17717224/169884745-006e2cd4-9633-4bf4-bcc9-d0a541c7442f.png)

**Comment by Mncdk** [comment]
NQ's recent changes to the radar has introduced a few issues that are out of players control, so until they are all fixed up on their end, it won't really be possible to fix everything. 
For that reason, a few of the fixes that are ready to go out to address the radar changes, have been sitting in BetaMod waiting for NQ to sort things out.

There was a client update this morning, so maybe NQ has fixed stuff/tried to fix stuff. We'll have to wait and see, I guess. :D

**Comment by ghost1257** [comment]
Ok sounds good thanks for the update
