### ISSUE TITLE
advanced torque control

### ISSUE THREAD

**Issue by SvarogZ** [Archaegeo/Archaegeo-Orbital-Hud#182]
Ship designs are not always well balanced. Standard torque control can give momentum to more than just one axis. It's more about roll and yaw than pitch.
Could you please implement the unwanted axis compensation with PID control?
This only makes sense for single-axis control if only one button is pressed.

For example:
if I press "Q" or "E", the "Forward" vector remains unchanged.
If I press "A" or "D", the "Up" vector remains unchanged.
If I press "W" or "S", the "Right" vector remains unchanged.

This behaviour may conflict with turnAssist in the atmosphere.

**Comment by Archaegeo** [comment]
Thats really meant to be ship design.  It would be a major overhaul/addition to counter for bad inertia matrix
