### ISSUE TITLE
IPH uses 30k to calculate travel time, while you are accelerating.

### ISSUE THREAD

**Issue by Mncdk** [Archaegeo/Archaegeo-Orbital-Hud#185]
As you accelerate towards a waypoint, the IPH tells you the estimated travel time, assuming you keep accelerating until you reach your maximum velocity.

When the max velocity is 20k, it still shows estimated travel time based on 30k (I assume) since it'll show ~35m while accelerating to something 80 SU away, and ~50m when reaching 20k km/h.

I figured I would put it here, so it's written down somewhere. Just in case NQ figures out wtf they wanna do. :P

**Comment by Archaegeo** [comment]
Fixed in 2.007
