### ISSUE TITLE
Crashes a lot more compred to version 1.6

### ISSUE THREAD

**Issue by tritan67** [Archaegeo/Archaegeo-Orbital-Hud#206]
Version 1.6 of autopilot would land better and enter atmosphere much safer. It crash more often. Is the math off since the speed changes that effected the game?

**Comment by Archaegeo** [comment]
No.  I have had no issues.  Do remember your pilot skills are much lower than they use to be, and UEF ships are not the best (and the builders dont have tier 5 skills yet either).
