### ISSUE TITLE
Even with a Beefy Machine, the HUD is slow/laggy

### ISSUE THREAD

**Issue by pedrohugorm** [Archaegeo/Archaegeo-Orbital-Hud#208]
I've been running the HUD with a PC with the Specs below:

AMD Ryzen 9 5950X 16-Core
GeForce 3080 TI
64 Ram

It's a beefy machine for DU, but yet the hud runs sluggishly.
Are there any recommended settings to improve performance?

I always notice a performance improvement when I alt + 3 - hiding the HUD.

Also, this seems to become worse if you tab in/out to open the menus of the game (Market, Schematics, etc).

Update:
I profiled the CPU and GPU - There's was no measurable difference in usage with the HUD on or off.
But the laggy behavior remains.

**Comment by uruskan** [comment]
I have r5 3600 and 2070 super no difference between normal hud or archud.

**Comment by Archaegeo** [comment]
I have no issues between vanilla or archhud.  Something else with your machine.
