### ISSUE TITLE
Issue with entry in atmosphere

### ISSUE THREAD

**Issue by marcoxavier33** [Archaegeo/Archaegeo-Orbital-Hud#209]
When i'm orbiting at 8000m ahead the planet, when the autopilot re entry, im going in atmo with 3K speed then destroying some components.

**Comment by Eld0r** [comment]
you have retro rocket brakes on your ship and brake force is higher than space engine thrust? you still need to built your ship autopilot save by yourself.

**Comment by Archaegeo** [comment]
Brakes.  Always more brakes.
