### ISSUE TITLE
Alt+3 To toggle Vanilla Widget view does not show vanilla Widgets

### ISSUE THREAD

**Issue by pedrohugorm** [Archaegeo/Archaegeo-Orbital-Hud#223]
With the version 2.012 when I press ALT+3 the vanilla widgets don't show up.
Before:
![image](https://user-images.githubusercontent.com/847076/197882955-2618db03-359f-4b08-8db0-162e58399dfb.png)
After:
![image](https://user-images.githubusercontent.com/847076/197883001-70fe5786-1cde-4613-9eab-64560a4d2f7f.png)

**Comment by Archaegeo** [comment]
RTFM, was a change :)
