### ISSUE TITLE
ArchHUD User’s Manual need some changes

### ISSUE THREAD

**Issue by tserj** [Archaegeo/Archaegeo-Orbital-Hud#224]
Private Locations section: 

1) "command `/createPrivate (all)`" should be replaced to "command `/createPrivate all`" as parameter "(all)" is not works

2) users need to be aware that privateFile name should be without extension ".lua", but file on the disk should have extension ".lua" as without this condition it won't works as expected.

**Comment by Archaegeo** [comment]
Parameters with () means optional
Will update #2
