### ISSUE TITLE
Quick Reference Menu

### ISSUE THREAD

**Issue by Maverick1000** [Archaegeo/Archaegeo-Orbital-Hud#238]
Not seeing the reference menu on the left upper of the window.

![image](https://user-images.githubusercontent.com/27829298/217361216-b421f3a4-aac4-473f-9be7-5f4fe5c5c3b2.png)

**Comment by Archaegeo** [comment]
It is working for me, recommend clicking the INFO button
![image](https://user-images.githubusercontent.com/30728822/217367223-6736046b-7f32-484f-9169-e22b7c3da8e9.png)

**Comment by Maverick1000** [comment]
thanks that work.  I must have click one the option that has a blank page.
