### ISSUE TITLE
About Route

### ISSUE THREAD

**Issue by Maverick1000** [Archaegeo/Archaegeo-Orbital-Hud#239]
The command "ALT-SHIFT-8"  depending how you do press those keys it think you what to turn on or off Decoupled Flight (Underwater)
Is there a lua command that I use for creating a route, if not, what would it take for you to adding some kind of interface doing it??????

**Comment by Archaegeo** [comment]
If you press it in the correct sequence, it will only add the current selected IPH to the WP.  Please bring discussions like this to the OSIN discord if you can.
