### ISSUE TITLE
AutoPilot Aliging

### ISSUE THREAD

**Issue by Maverick1000** [Archaegeo/Archaegeo-Orbital-Hud#241]
When take off and going from planet to plane with autopilot the following message is shown "Attempting to clear los between Alioth  and waypoint" it stay up way after I have left the planet atmosphere

**Comment by Maverick1000** [comment]
Not sure if the following screen shot would cause the that string to say up 

![image](https://user-images.githubusercontent.com/27829298/222893480-78e4f06f-1d4c-444f-af33-9a2592df705d.png)

**Comment by Archaegeo** [comment]
Grab the apclass.lua found in the BetaMod branch (or in the OSIN Discord channel).  It fixes this issue.
