### ISSUE TITLE
Openning lua parameters crash the game

### ISSUE THREAD

**Issue by krateria** [Archaegeo/Archaegeo-Orbital-Hud#84]
Openning lua parameters crash the game. 
Can be reproduced in or out of the seat.

**Comment by JamesFlames** [comment]
Damage Report also insta-crashes to desktop when you edit the Lua Parameters, its not just ArchHud.

**Comment by Nadbreath** [comment]
hi
I'm having the same issues as 'krateria

**Comment by krateria** [comment]
> 
> 
> hi
> I'm having the same issues as 'krateria

This is most likely a NQ problem, as other script related things are crashing the game just like Archaegeo.
